name: ES Cluster

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure VM for Elasticsearch
        run: sudo sysctl -w vm.max_map_count=262144
      - name: docker-compose Up Cluster
        run: docker-compose -f docker-compose-es-cluster.yml up -d --remove-orphans
      - name: Wait
        run: sleep 30
      - name: Docker ps
        run: docker-compose ps
      - name: Docker logs
        run: docker-compose logs elaticsearch2
      - name: Test Cluster
        run: curl -f -LI http://localhost:9200/_cluster/health?pretty
