name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Stop MySql
        run: sudo service mysql stop
      - name: Configure VM for Elasticsearch
        run: sudo sysctl -w vm.max_map_count=262144
      - name: docker-compose build app
        run: docker-compose build app
      - name: Run docker-compose
        run: docker-compose up -d
      - name: Wait
        run: sleep 30
      - name: Test App
        run: curl -f -LI -X POST http://localhost:8080/create
